[package]
name = "clocked"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
midir = "0.8.0"
rtrb = "0.2.3"
rubato = "0.14.1"
smallvec = "1.11.0"

[dev-dependencies]
hound = "3.5.0"
